//
//  Channel.swift
//  API
//
//  Created by Zach McGaughey on 5/9/19.
//  Copyright © 2019 Zach McGaughey. All rights reserved.
//

import ObjectMapper

public struct Channel: ImmutableMappable {

  public let author: String
  public let authorId: String
  public let authorUrl: URL
  public let authorBanners: [AuthorThumbnail]
  public let authorThumbnails: [AuthorThumbnail]

  public let subCount: UInt
  public let totalViews: UInt
  public let joined: Date

  public let paied: Bool?
  public let autoGenerated: Bool
  public let isFamilyFriendly: Bool
  public let channelDescription: String
  public let channelDescriptionHtml: String
  public let allowedRegions: [String]

  public let latestVideos: [VideoPreview]
  public let relatedChannels: [ChannelPreview]

  public init(map: Map) throws {
    author = try map.value("author")
    authorId = try map.value("authorId")
    authorUrl = try map.value("authorUrl", using: URLTransform())
    authorBanners = try map.value("authorBanners")
    authorThumbnails = try map.value("authorThumbnails")

    subCount = try map.value("subCount")
    totalViews = try map.value("totalViews")
    joined = try map.value("joined", using: DateTransform())

    paied = try map.value("paid")
    autoGenerated = try map.value("autoGenerated")
    isFamilyFriendly = try map.value("isFamilyFriendly")
    channelDescription = try map.value("description")
    channelDescriptionHtml = try map.value("descriptionHtml")
    allowedRegions = try map.value("allowedRegions")

    latestVideos = try map.value("latestVideos")
    relatedChannels = try map.value("relatedChannels")
  }

}
